#!/bin/bash

#Define colors
normal=$(echo -en "\e[0m")
orange=$(echo -en "\e[33m")
aqua=$(echo -en "\e[36m")
lightgreen=$(echo -en "\e[92m")

rm guo >/dev/null 2>&1
rm /usr/local/bin/guo >/dev/null 2>&1
curl https://raw.githubusercontent.com/guosasipo/global_index_source/master/guo >guo 2>/dev/null
mv guo /usr/local/bin
chmod +x /usr/local/bin/guo

if ! command -v guo &>/dev/null; then
    echo "${orange}Installation Failed !!!"
    echo "Posssible Solution : Run as root or check non-root version.${normal}"
    exit
else
    guo
fi
